# Generated by Django 5.1.7 on 2025-03-30 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_user_alter_post_author_alter_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog_images/default.jpg', upload_to='blog_images/'),
        ),
    ]
