# Generated by Django 5.1.7 on 2025-04-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_remove_comment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
