# Generated by Django 5.1.7 on 2025-04-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_comment_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="subject",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
